### ISSUE TITLE
Minimal install/run steps in README.md.

### ISSUE THREAD

**Issue by RhysU** [amirouche/zk#1]
Saw your announce on the chez-scheme lists and wanted to kick the tires.  From a fresh clone...
```
$ uname -a
Linux telegonus 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ akku update
[info] Fetching index from https://archive.akkuscm.org/archive/ ...
...
[info] Index updated

[1023 rhys@telegonus master zk]$ akku install
[info] Fetching pfds
...
[info] Installing .akku/bin/activate

[1024 rhys@telegonus master zk]$ source .akku/bin/activate 
```
...after which I see:
```
[1025 rhys@telegonus master zk]$ chezscheme9.5 zk.scm 
Chez Scheme Version 9.5
Copyright 1984-2017 Cisco Systems, Inc.

Exception: (while loading /usr/local/lib/libtermbox.so.1) /usr/local/lib/libtermbox.so.1: cannot open shared object file: No such file or directory
```
I got that libtermbox.so.1 prereq sorted after some digging.  May be worth pointing to https://github.com/nsf/termbox within your README.md, as termbox doesn't seem to be running around in all the popular Linux distros these days.

**Comment by amirouche** [comment]
Sorry for the poor experience, I will work on improving the situation.

**Comment by amirouche** [comment]
It requires libtermbox with truecolor support:

```
git clone https://github.com/amirouche/termbox-truecolor
cd termbox-truecolor
git checkout truecolor
```

Then follow the `waf` instruction to install termbox this way. Right I don't rely on truecolor support but I plan to. It seems you have `akku` then after installing the dependencies using akku, you can run the program with `scheme zk.scm` to quit type `Ctrl+Q`, saving doesn't work as of right now.

Thanks for trying my project :100:

**Comment by amirouche** [comment]
@RhysU let me know if something is unclear in the new [README](https://github.com/amirouche/zk#getting-started).

I am thinking about dropping akku dependency, but I am not sure... What do you think?

**Comment by RhysU** [comment]
Thank you!  No need to apologize for the experience.  The new README is wonderfully informative.

**Comment by RhysU** [comment]
Akku seems quite reasonable.
